name: RodaliesPlus
version: ${project.version}
build: ${project.cibuild}
author: JugonDavidListo
main: me.jugondavidlisto.rodaliesplus.metro.Console
description: Metro System

commands:
  metroplus:
    description: MetroPlus plugin base command.
    
permissions:
    metroplus.viewcmd:
        description: View Help in CMD.
        default: op
    metroplus.createTicketSign:
        description: Create the ticket sign.
        default: op
    metroplus.useTicketSign:
        description: Use the ticket sign.
        default: op
    metroplus.createFaregateSign:
        description: Create faregates sign.
        default: op
    metroplus.useFaregateSign:
        description: Use faregates Sign.
        default: op
    

